version: "3.5"

services:

  web:

    image: drupal:8.2

    ports:
      - "8080:80"

    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  db:

    image: postgres:9.6

    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
      POSTGRES_USER: postgres

    secrets:
      - psql-pw

    volumes:
      - drupal-pgdata:/var/lib/postgresql/data
    
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-pgdata:

secrets:
  psql-pw:
    external: true
