version: "3.5"

services:
    # docker container run --rm -v `pwd`:`pwd` -w `pwd` -ti -h ansible jkedra/ansible
    control:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile-control
        volumes:
            - .:/ansible

    lb01:
        image: alpine:latest
        stdin_open: true
        tty: true
 
    app01:
        image: alpine:latest
        stdin_open: true
        tty: true
 
    app02:
        image: alpine:latest
        stdin_open: true
        tty: true
 
    db01:
        image: alpine:latest
        stdin_open: true
        tty: true
        
    

#    ports:
#      - "8080:80"
#    volumes:
#      - drupal-modules:/var/www/html/modules
#      - drupal-profiles:/var/www/html/profiles
#      - drupal-sites:/var/www/html/sites
#      - drupal-themes:/var/www/html/themes

#  db:
#
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#    volumes:
#      - drupal-pgdata:/var/lib/postgresql/data
    
#volumes:
#  drupal-modules:
#  drupal-profiles:
#  drupal-sites:
#  drupal-themes:
#  drupal-pgdata:
